apiVersion: apps/v1
kind: Deployment
metadata:
  name: gramine-mpspdz-tee-remote
  labels:
    app: gramine-mpspdz-tee-remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gramine-mpspdz-tee-remote
  template:
    metadata:
      labels:
        app: gramine-mpspdz-tee-remote
    spec:
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      containers:
      - name: gramine-mpspdz-tee
        image: ghcr.io/datakaveri/gramine-base:mpspdz-tee-a72d129
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "gramine-sgx-gen-private-key; while true; do sleep 30; done;" ]
        resources:
          limits:
            sgx.intel.com/epc: "512Mi"
        volumeMounts:
        - name: var-run-aesmd
          mountPath: /var/run/aesmd
      restartPolicy: "Always"
      volumes:
      - name: var-run-aesmd
        hostPath:
          path: /var/run/aesmd
